// Generated by CoffeeScript 1.9.2
(function() {
  exports.schema = {
    name: 'flash_calculated',
    fields: {
      flash_load: 'integer',
      cms: 'integer',
      dispatch: 'integer',
      ad: 'integer',
      ad_end: 'integer',
      video_load: 'integer',
      play: 'integer',
      vv: 'integer',
      time_start: 'bigInteger',
      time_end: 'bigInteger',
      time_type: ''
    }
  };

}).call(this);

//# sourceMappingURL=flash_calculated.js.map
